Homework
deopinc/git-homework-enezihe pull request #2
Opened 2022-09-23 16:50 UTC by enezihe

Please checkout my homework.

2022-09-23 17:03 UTC, ahmetaslan13 requested changes
Needs to delete submodule.

2022-09-23 20:06 UTC, ramazanatalay reviewed
That is pretty good. Keep up the good work.

2022-09-23 20:07 UTC, ramazanatalay approved these changes
You can merge to main now.

2022-09-24 12:41 UTC, enezihe commented
Read.md isim yazildi

2022-09-24 12:41 UTC, closed without merging